Movie cards@feat
WildCodeSchool-2024-02/JS-RMT-julien-TeamC-Project2 pull request #2
Opened 2024-05-23 15:08 UTC by lub04

composant carte avec style qui se répète avec la data

2024-05-23 15:28 UTC, NessaGi submitted a review, later dismissed

2024-05-23 15:37 UTC, JohnnyDomingues submitted a review, later dismissed

2024-05-24 09:51 UTC, jujuck requested changes

2024-05-24 09:51 UTC, jujuck commented on client/src/components/MovieCard/MovieCard.jsx
> +import { Link } from "react-router-dom";
Attention, ordre des imprts
En premier les modules puis les pages/components, puis css ou assets

2024-05-24 09:51 UTC, jujuck commented on client/src/components/MovieCard/MovieCard.jsx
> +      <Link to={`http://localhost:3000/movies/${movie.title}`}>
sur le link, pas besoin de préciser localhost:3000, pas besoin de domain

2024-05-24 09:51 UTC, jujuck commented on client/src/components/MovieCard/movie-card.css
> +    box-shadow: 8px 10px 15px 5px rgba(66, 66, 66, 0.61);
créer une classe globale

2024-05-24 09:51 UTC, jujuck commented on client/src/components/MovieCard/movie-card.css
> +    a {
mettre le a text-decoration en global

2024-05-24 09:51 UTC, jujuck commented on client/src/main.jsx
> +      axios.get("http://localhost:3310/api/movies").then((res) => res.data),
mettre ton domain en .env

2024-05-24 13:04 UTC, AnnDo33 approved these changes

2024-05-24 13:05 UTC, NessaGi approved these changes

2024-05-24 15:24 UTC, jujuck approved these changes

2024-05-24 15:24 UTC, merged