Movie details@feat
WildCodeSchool-2024-02/JS-RMT-julien-TeamC-Project2 pull request #3
Opened 2024-05-23 15:26 UTC by JohnnyDomingues

2024-05-23 15:28 UTC, lub04 commented on client/src/components/MovieDetailCard/MovieDetail.css
> +  box-sizing: border-box;
les lignes 2 à 4 ont déja été configuré en amont pas besoin de les réécrire ici

2024-05-24 06:42 UTC, lub04 commented on client/src/components/MovieDetailCard/MovieDetail.css
> +}
Tout ce qu'il y a dans le body doit être mis ailleur pour ne pas affecter le reste des composants. dans le body on ne doit mettre que ce qui est général à tous le site internet.

2024-05-24 06:42 UTC, lub04 commented on client/src/components/MovieDetailCard/MovieDetail.css
> +}
réorganisation du CSS nécéssaire pour permettre un gain de compétences à  ce niveau

2024-05-24 06:46 UTC, lub04 commented on client/src/components/MovieDetailCard/MovieDetailCard.jsx
> +        </div>
la div "movie-detail-subcard" est un composant unique qui se répète avec un changement de datas tu ne respecte pas le DRY

2024-05-24 06:48 UTC, lub04 commented on client/src/components/MovieDetailCard/MovieDetailCard.jsx
> +      <div className="MovieDetail-info">
pourquoi faire des div pour n'y mettre qu'un seul élément

2024-05-24 06:51 UTC, lub04 commented on client/src/components/MovieDetailCard/MovieDetailCard.jsx
> +  useEffect(() => {
Y a t-il une raison particulière pour utiliser use effect plutôt qu'un loader ?

2024-05-24 06:53 UTC, lub04 requested changes
des choses à revoir avant de merge dsl

2024-05-24 10:03 UTC, jujuck requested changes

2024-05-24 10:03 UTC, jujuck commented on client/src/components/MovieDetailCard/MovieDetail.css
> +.MovieDetail-container {
Reprendre la convention de nommage

2024-05-24 10:03 UTC, jujuck commented on client/src/main.jsx
> +        `http://localhost:3310/api/movies/${params.title}`
passer en .env pour le localhost

2024-05-24 10:03 UTC, jujuck commented on client/src/pages/MovieDetail.jsx
> +    <div>
POurquoi une div ?

2024-05-24 10:03 UTC, jujuck commented on server/app/router.js
> +    res.status(404).json({ message: "Movie not found" });
As tu testé ?

2024-05-27 06:43 UTC, lub04 commented on client/src/components/MovieDetailCard/MovieDetailCard.jsx
> +
l'ordre de tes imports est incorect, il faut mettre dans l'orde : les modules, puis les composants, et enfin le CSS et les assets

2024-05-27 06:47 UTC, lub04 requested changes
il faut juste revoir l'ordre des imports dans MovieDetailCard.jsx  (inverser les lignes 2 et 3) et faire le responsive

2024-05-27 15:13 UTC, lub04 commented on client/src/components/MovieDetailCard/MovieDetail.css
> +}
faire le responsive

2024-05-27 15:16 UTC, lub04 commented on client/src/components/MovieDetailCard/MovieDetailCard.jsx
> +  ];
rajouter la note sur 10 accompagnée du nombre d'avis

2024-05-28 09:05 UTC, lub04 submitted a review, later dismissed

2024-05-28 09:07 UTC, AnnDo33 submitted a review, later dismissed

2024-05-28 13:38 UTC, jujuck requested changes

2024-05-28 13:38 UTC, jujuck commented on client/src/pages/MovieDetail.jsx
> +  return <MovieDetailCard />;
La page movie detail est là pour articuler l'ensemble des éléments composant ta page. Si ta page n'est composé que d'un element JSX, qui est un sub component, alors l'un des 2 est de trop.

2024-05-28 13:38 UTC, jujuck commented on client/src/components/MovieDetailCard/MovieDetailCard.jsx
> +import { useLoaderData } from "react-router-dom";
Remonte tout ceci dans ta page MovieDetail.jsx

2024-05-28 14:45 UTC, JohnnyDomingues commented on client/src/pages/MovieDetail.jsx
> +  return <MovieDetailCard />;
C'est une page, car lors du merge, il y aura l'intégration du header et du footer.

2024-05-28 14:51 UTC, lub04 submitted a review, later dismissed

2024-05-28 14:54 UTC, lub04 approved these changes, later dismissed

2024-05-29 07:07 UTC, AnnDo33 submitted a review, later dismissed

2024-05-29 08:02 UTC, lub04 approved these changes

2024-05-29 08:06 UTC, NessaGi approved these changes

2024-05-29 08:32 UTC, jujuck approved these changes

2024-05-29 08:32 UTC, merged