Navigation@feat
WildCodeSchool-2024-02/JS-RMT-julien-TeamC-Project2 pull request #4
Opened 2024-05-27 14:50 UTC by NessaGi

Branche composée d'un header avec des boutons de navigation menant aux autres pages.

2024-05-27 15:03 UTC, lub04 commented on client/index.html
> +    <title>Film Paradise, le ciné dans ton canapé</title>
fait partie de la config globale et n'es pas nécéssaire dans ta feature

2024-05-27 15:03 UTC, lub04 commented on client/index.html
> +    </style>
pourquoi ?

2024-05-27 15:04 UTC, lub04 commented on client/src/App.jsx
> +      <Header />
pourquoi mettre une div et pas une balise header ?

2024-05-27 15:06 UTC, lub04 commented on client/src/components/header/header.css
> +}
il manque le responsive

2024-05-27 15:08 UTC, lub04 commented on client/src/components/header/header.css
> +  background-color: #2f1a57;
tu as laissé le background-color alors qu'on avait convenu de le laisser transparent et de mettre une image qui couvre tout le site

2024-05-27 15:09 UTC, lub04 commented on client/src/components/header/header.css
> +    text-decoration: none;
tu peux enlever cette ligne sur les a car à a rajouter sur une branche config générale sur tout le site

2024-05-27 15:11 UTC, lub04 commented on client/src/assets/images/BackgroundFilmParadise.png
Au final nous avons décidé de ne pas utiliser cette image

2024-05-27 15:13 UTC, lub04 requested changes
quelques points à revoirs

2024-05-28 09:30 UTC, NessaGi commented on client/index.html
> +    <title>Film Paradise, le ciné dans ton canapé</title>
ok

2024-05-28 09:31 UTC, NessaGi commented on client/index.html
> +    </style>
parceque j'ai pas réussi à la faire prendre en compte autrement

2024-05-28 09:32 UTC, NessaGi commented on client/src/App.jsx
> +      <Header />
parceque de base il y avait également la nav.
je peux la retirer..

2024-05-28 10:09 UTC, NessaGi commented on client/src/components/header/header.css
> +}
done

2024-05-28 13:13 UTC, lub04 submitted a review, later dismissed

2024-05-28 13:24 UTC, AnnDo33 submitted a review, later dismissed

2024-05-28 13:24 UTC, JohnnyDomingues submitted a review, later dismissed

2024-05-29 06:56 UTC, jujuck requested changes

2024-05-29 06:56 UTC, jujuck commented on client/src/components/header/Header.jsx
> +      <section className="action-buttons">
Plutot mettre une balise nav que section

2024-05-29 07:52 UTC, lub04 approved these changes

2024-05-29 08:04 UTC, AnnDo33 approved these changes

2024-05-29 08:22 UTC, jujuck approved these changes

2024-05-29 08:22 UTC, merged